name: background_job_repository
description: Package accessing the background_job
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  background_fetch: ^1.1.0
  database_client:
    path: ../database_client
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^10.0.0-dev.17
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  steps_client:
    path: ../steps_client

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
