name: app_ui
description: UI Toolkit for the App Flutter Application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  gap: ^2.0.0
  infinite_listview: ^1.1.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  fonts:
    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/BarlowCondensed-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/BarlowCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BarlowCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BarlowCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/BarlowCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/BarlowCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/BarlowCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/BarlowCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/BarlowCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BarlowCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/BarlowCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/BarlowCondensed-ThinItalic.ttf
          weight: 100
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
