name: files_repository
description: Package accessing the files
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  csv: ^5.0.1
  equatable: ^2.0.3
  file_picker: ^5.0.0
  path: ^1.8.1
  rxdart: ^0.27.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
