name: database_client
description: Package connecting to the local database
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.11
  drift_dev: ^1.7.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
